export const APP_NAME = "ZPP Connect";

export * from "./access-contracts.js";

export const defaultProfile = {
  id: "lot-zpp",
  organizationName: "LOT Polish Airlines",
  appSubtitle: "Family Assistance & Reunification Tool for LOT Polish Airlines",
  genericSubtitle: "Family Assistance, Next-of-Kin Matching and Reunification Platform",
  teamName: "ZPP — Zespół Pomocy Poszkodowanym",
  contactEmail: "erp@lot.pl",
  author: "Sebastian Ossoliński, 2026",
  footerText:
    "ZPP Connect. Family Assistance & Reunification Tool for LOT Polish Airlines. Contact: erp@lot.pl. Author: Sebastian Ossoliński, 2026",
  recordTerminology: {
    enquiry: "TEC enquiry",
    familyRecord: "Family/NOK/FRC record",
    passengerRecord: "Passenger/Crew/SRC record",
    matchingRecord: "Matching record",
    request: "Welfare/logistics request"
  },
  exerciseLabels: {
    exercise: "EXERCISE DATA",
    training: "TRAINING DATA",
    real: "REAL ACTIVATION"
  }
} as const;

export const defaultOrganizations = [
  {
    key: "lot",
    name: "LOT Polish Airlines",
    type: "Airline",
    status: "Active",
    contactEmail: "erp@lot.pl",
    description: "Primary airline organization operating ZPP Connect."
  },
  {
    key: "zpp",
    name: "Zespół Pomocy Poszkodowanym",
    type: "Response team",
    status: "Active",
    contactEmail: "erp@lot.pl",
    description: "Family assistance and reunification response team."
  },
  {
    key: "tec",
    name: "Telephone Enquiry Centre",
    type: "Support unit",
    status: "Active",
    contactEmail: "tec@lot.pl",
    description: "Call intake and enquiry triage desk."
  }
] as const;

export const permissions = {
  "session:read": "Read sessions",
  "session:create": "Create sessions",
  "session:update": "Update sessions",
  "session:close": "Close sessions",
  "incident:members:read": "Read incident assignments",
  "incident:members:manage": "Assign, revoke and reactivate incident access",
  "enquiry:read": "Read enquiries",
  "enquiry:create": "Create enquiries",
  "enquiry:update": "Update enquiries",
  "enquiry:escalate": "Escalate urgent enquiries",
  "enquiry:close": "Close enquiries",
  "family:read": "Read family/NOK records",
  "family:create": "Create family/NOK records",
  "family:update": "Update family/NOK records",
  "family:verify": "Verify family/NOK status",
  "passenger:read": "Read passenger/crew records",
  "passenger:create": "Create passenger/crew records",
  "passenger:update": "Update passenger/crew records",
  "passenger:srcConfirm": "Mark SRC confirmation",
  "passenger:control": "Change passenger condition and hold decisions",
  "matching:read": "Read matching records",
  "matching:create": "Create potential matches",
  "matching:verify": "Verify matches",
  "matching:reject": "Reject matches",
  "matching:hold": "Create holds/escalations",
  "matching:clearHold": "Clear holds",
  "release:read": "Read reunification/release records",
  "release:prepare": "Prepare reunification/release",
  "release:check": "Record independent release checks",
  "release:authorize": "Authorize reunification/release",
  "release:complete": "Complete reunification/release",
  "release:cancel": "Cancel pending release action",
  "request:read": "Read requests",
  "request:create": "Create requests",
  "request:update": "Update requests",
  "request:assign": "Assign requests",
  "request:close": "Close requests",
  "assignment:read": "Read assignments",
  "assignment:create": "Create assignments",
  "assignment:update": "Update assignments",
  "assignment:assign": "Assign task owners",
  "member:read": "Read member profiles",
  "member:create": "Create member profiles",
  "member:update": "Update member profiles",
  "member:archive": "Archive member profiles",
  "member:link-user": "Link member profiles to user accounts",
  "group:read": "Read response groups",
  "group:create": "Create response groups",
  "group:update": "Update response groups",
  "group:archive": "Archive response groups",
  "group:membership:manage": "Manage response group membership",
  "roster:read": "Read all roster shifts",
  "roster:read-own": "Read own roster shifts",
  "roster:create": "Create roster shifts",
  "roster:update": "Update roster shifts",
  "roster:publish": "Publish roster shifts",
  "roster:cancel": "Cancel roster shifts",
  "roster:complete": "Complete roster shifts",
  "roster:confirm-own": "Confirm own roster shifts",
  "roster:decline-own": "Decline own roster shifts",
  "availability:read-own": "Read own availability",
  "availability:update-own": "Update own availability",
  "availability:read-all": "Read all availability",
  "availability:manage-all": "Manage all availability",
  "training:read-own": "Read own training",
  "training:read-all": "Read all training",
  "training:course:manage": "Manage training courses",
  "training:requirement:manage": "Manage training requirements",
  "training:assign": "Assign training",
  "training:complete-own": "Complete own training",
  "training:complete-all": "Record training completion",
  "training:verify": "Verify training completion",
  "training:waive": "Waive training requirements",
  "document:read-own": "Read own required documents",
  "document:read-all": "Read document library and compliance records",
  "document:manage": "Manage documents",
  "document:version:manage": "Manage document versions",
  "document:publish": "Publish or withdraw document versions",
  "document:requirement:manage": "Manage document requirements",
  "document:acknowledge-own": "Acknowledge own documents",
  "document:acknowledge-all": "Record document acknowledgements",
  "document:audit:read": "Read document acknowledgement audit",
  "readiness:read-own": "Read own readiness",
  "readiness:read-group": "Read group readiness",
  "readiness:read-all": "Read all readiness",
  "readiness:read-summary": "Read readiness summary",
  "readiness:policy:read": "Read readiness policy",
  "readiness:policy:manage": "Manage readiness policy",
  "briefing:read": "Read current operational briefing",
  "briefing:read-history": "Read briefing revision history",
  "briefing:create-draft": "Create briefing drafts",
  "briefing:update-draft": "Update briefing drafts",
  "briefing:publish": "Publish briefing revisions",
  "briefing:audit:read": "Read briefing audit trail",
  "timeline:read": "Read case timeline",
  "timeline:create": "Create notes/timeline events",
  "audit:read": "Read audit log",
  "import:create": "Import data",
  "export:create": "Export data",
  "exercise:manage": "Manage exercise injects and observations",
  "reports:read": "Read reports",
  "admin:manage": "Manage organizations, users, roles, dictionaries and profile"
} as const;

export type Permission = keyof typeof permissions;

export type RoleScopeType = "GLOBAL" | "GROUP";
export type RolePool = "ZPP" | "TEC" | "ALL";

export const roleAliases: Record<string, string> = {
  admin: "system-admin",
  "system admin": "system-admin",
  coordinator: "zpp-coordinator",
  "crisis coordinator": "zpp-coordinator",
  "zpp coordinator": "zpp-coordinator",
  "tec coordinator": "tec-coordinator",
  zpp: "zpp-group-leader",
  "zpp leader": "zpp-group-leader",
  "zpp group leader": "zpp-group-leader",
  "tec group leader": "tec-group-leader",
  tec: "tec-member",
  "tec operator": "tec-member",
  "tec member": "tec-member",
  volunteer: "zpp-member",
  member: "zpp-member",
  "zpp member": "zpp-member",
  viewer: "observer"
};

export function normalizeRoleName(roleName: string) {
  const normalized = roleName.trim().toLowerCase();
  return roleAliases[normalized] ?? normalized;
}

export const defaultRoles: Array<{
  name: string;
  displayName: string;
  description: string;
  permissions: Permission[];
  scopeTypes: RoleScopeType[];
  pool?: RolePool;
  operationalRole: boolean;
}> = [
  {
    name: "system-admin",
    displayName: "System Admin",
    description: "Manages users, roles, configuration and audit review without automatic operational coordinator authority.",
    permissions: [
      "session:read",
      "incident:members:read",
      "incident:members:manage",
      "readiness:policy:read",
      "readiness:policy:manage",
      "document:audit:read",
      "audit:read",
      "reports:read",
      "admin:manage"
    ],
    scopeTypes: ["GLOBAL"],
    pool: "ALL",
    operationalRole: false
  },
  {
    name: "zpp-coordinator",
    displayName: "ZPP Coordinator",
    description: "Global ZPP operational coordination, controlled disclosure workflows, readiness and handover oversight.",
    permissions: [
      "session:read",
      "session:create",
      "session:update",
      "session:close",
      "incident:members:read",
      "incident:members:manage",
      "enquiry:read",
      "enquiry:create",
      "enquiry:update",
      "enquiry:escalate",
      "enquiry:close",
      "family:read",
      "family:create",
      "family:update",
      "family:verify",
      "passenger:read",
      "passenger:create",
      "passenger:update",
      "passenger:srcConfirm",
      "passenger:control",
      "matching:read",
      "matching:create",
      "matching:verify",
      "matching:reject",
      "matching:hold",
      "matching:clearHold",
      "release:read",
      "release:prepare",
      "release:check",
      "release:authorize",
      "release:complete",
      "release:cancel",
      "request:read",
      "request:create",
      "request:update",
      "request:assign",
      "request:close",
      "assignment:read",
      "assignment:create",
      "assignment:update",
      "assignment:assign",
      "member:read",
      "member:create",
      "member:update",
      "member:archive",
      "member:link-user",
      "group:read",
      "group:create",
      "group:update",
      "group:archive",
      "group:membership:manage",
      "roster:read",
      "roster:read-own",
      "roster:create",
      "roster:update",
      "roster:publish",
      "roster:cancel",
      "roster:complete",
      "roster:confirm-own",
      "roster:decline-own",
      "availability:read-own",
      "availability:update-own",
      "availability:read-all",
      "availability:manage-all",
      "training:read-own",
      "training:read-all",
      "training:course:manage",
      "training:requirement:manage",
      "training:assign",
      "training:complete-own",
      "training:complete-all",
      "training:verify",
      "training:waive",
      "document:read-own",
      "document:read-all",
      "document:manage",
      "document:version:manage",
      "document:publish",
      "document:requirement:manage",
      "document:acknowledge-own",
      "document:acknowledge-all",
      "document:audit:read",
      "readiness:read-own",
      "readiness:read-group",
      "readiness:read-all",
      "readiness:read-summary",
      "readiness:policy:read",
      "briefing:read",
      "briefing:read-history",
      "briefing:create-draft",
      "briefing:update-draft",
      "briefing:publish",
      "briefing:audit:read",
      "timeline:read",
      "timeline:create",
      "audit:read",
      "import:create",
      "export:create",
      "exercise:manage",
      "reports:read"
    ],
    scopeTypes: ["GLOBAL"],
    pool: "ZPP",
    operationalRole: true
  },
  {
    name: "tec-coordinator",
    displayName: "TEC Coordinator",
    description: "Global TEC coordination for call intake, enquiry handover, TEC staffing and readiness oversight.",
    permissions: [
      "session:read",
      "session:create",
      "session:update",
      "incident:members:read",
      "enquiry:read",
      "enquiry:create",
      "enquiry:update",
      "enquiry:escalate",
      "enquiry:close",
      "family:read",
      "passenger:read",
      "matching:read",
      "request:read",
      "request:create",
      "request:update",
      "request:assign",
      "request:close",
      "assignment:read",
      "assignment:create",
      "assignment:update",
      "assignment:assign",
      "member:read",
      "member:create",
      "member:update",
      "member:archive",
      "member:link-user",
      "group:read",
      "group:create",
      "group:update",
      "group:archive",
      "group:membership:manage",
      "roster:read",
      "roster:read-own",
      "roster:create",
      "roster:update",
      "roster:publish",
      "roster:cancel",
      "roster:complete",
      "roster:confirm-own",
      "roster:decline-own",
      "availability:read-own",
      "availability:update-own",
      "availability:read-all",
      "availability:manage-all",
      "training:read-own",
      "training:read-all",
      "training:requirement:manage",
      "training:assign",
      "training:complete-own",
      "training:complete-all",
      "training:verify",
      "document:read-own",
      "document:read-all",
      "document:requirement:manage",
      "document:acknowledge-own",
      "document:acknowledge-all",
      "readiness:read-own",
      "readiness:read-group",
      "readiness:read-summary",
      "readiness:policy:read",
      "briefing:read",
      "briefing:read-history",
      "briefing:create-draft",
      "briefing:update-draft",
      "briefing:publish",
      "briefing:audit:read",
      "timeline:read",
      "timeline:create",
      "import:create",
      "export:create",
      "exercise:manage",
      "reports:read"
    ],
    scopeTypes: ["GLOBAL"],
    pool: "TEC",
    operationalRole: true
  },
  {
    name: "zpp-group-leader",
    displayName: "ZPP Group Leader",
    description: "Leads assigned ZPP groups and manages scoped members, roster coverage and assigned work.",
    permissions: [
      "session:read",
      "assignment:read",
      "assignment:create",
      "assignment:update",
      "assignment:assign",
      "member:read",
      "member:update",
      "member:archive",
      "group:read",
      "group:update",
      "group:archive",
      "group:membership:manage",
      "roster:read",
      "roster:read-own",
      "roster:create",
      "roster:update",
      "roster:publish",
      "roster:cancel",
      "roster:complete",
      "roster:confirm-own",
      "roster:decline-own",
      "availability:read-own",
      "availability:update-own",
      "availability:read-all",
      "availability:manage-all",
      "training:read-own",
      "training:read-all",
      "training:requirement:manage",
      "training:assign",
      "training:complete-own",
      "training:complete-all",
      "training:verify",
      "document:read-own",
      "document:read-all",
      "document:requirement:manage",
      "document:acknowledge-own",
      "document:acknowledge-all",
      "readiness:read-own",
      "readiness:read-group",
      "readiness:read-summary",
      "readiness:policy:read",
      "briefing:read",
      "briefing:read-history"
    ],
    scopeTypes: ["GROUP"],
    pool: "ZPP",
    operationalRole: true
  },
  {
    name: "tec-group-leader",
    displayName: "TEC Group Leader",
    description: "Leads assigned TEC groups and manages scoped intake staffing, coverage and handover work.",
    permissions: [
      "session:read",
      "assignment:read",
      "assignment:create",
      "assignment:update",
      "assignment:assign",
      "member:read",
      "member:update",
      "member:archive",
      "group:read",
      "group:update",
      "group:archive",
      "group:membership:manage",
      "roster:read",
      "roster:read-own",
      "roster:create",
      "roster:update",
      "roster:publish",
      "roster:cancel",
      "roster:complete",
      "roster:confirm-own",
      "roster:decline-own",
      "availability:read-own",
      "availability:update-own",
      "availability:read-all",
      "availability:manage-all",
      "training:read-own",
      "training:read-all",
      "training:requirement:manage",
      "training:assign",
      "training:complete-own",
      "training:complete-all",
      "training:verify",
      "document:read-own",
      "document:read-all",
      "document:requirement:manage",
      "document:acknowledge-own",
      "document:acknowledge-all",
      "readiness:read-own",
      "readiness:read-group",
      "readiness:read-summary",
      "readiness:policy:read",
      "briefing:read",
      "briefing:read-history"
    ],
    scopeTypes: ["GROUP"],
    pool: "TEC",
    operationalRole: true
  },
  {
    name: "zpp-member",
    displayName: "ZPP Member",
    description: "Works on assigned ZPP tasks, personal availability, training, documents and briefings.",
    permissions: [
      "session:read",
      "member:read",
      "group:read",
      "roster:read-own",
      "roster:confirm-own",
      "roster:decline-own",
      "availability:read-own",
      "availability:update-own",
      "training:read-own",
      "training:complete-own",
      "document:read-own",
      "document:acknowledge-own",
      "readiness:read-own",
      "briefing:read",
      "assignment:read",
      "assignment:update"
    ],
    scopeTypes: ["GLOBAL"],
    pool: "ZPP",
    operationalRole: true
  },
  {
    name: "tec-member",
    displayName: "TEC Member",
    description: "Handles TEC intake and personal work without ZPP verification or release authority.",
    permissions: [
      "session:read",
      "enquiry:read",
      "enquiry:create",
      "enquiry:update",
      "enquiry:escalate",
      "enquiry:close",
      "family:read",
      "request:read",
      "request:create",
      "assignment:read",
      "roster:read-own",
      "roster:confirm-own",
      "roster:decline-own",
      "availability:read-own",
      "availability:update-own",
      "training:read-own",
      "training:complete-own",
      "document:read-own",
      "document:acknowledge-own",
      "readiness:read-own",
      "briefing:read",
      "timeline:read",
      "timeline:create"
    ],
    scopeTypes: ["GLOBAL"],
    pool: "TEC",
    operationalRole: true
  },
  {
    name: "observer",
    displayName: "Observer",
    description: "Read-only operational overview for observers and training viewers.",
    permissions: [
      "session:read",
      "roster:read",
      "training:read-all",
      "document:read-all",
      "readiness:read-summary",
      "briefing:read"
    ],
    scopeTypes: ["GLOBAL"],
    pool: "ALL",
    operationalRole: false
  }
];

export const dictionaries = {
  sessionModes: ["REAL", "EXERCISE", "TRAINING"],
  sessionStatuses: ["Draft", "Active", "Paused", "Closed", "Archived"],
  eventTypes: [
    "Aircraft accident",
    "Serious incident",
    "Airport emergency",
    "Mass disruption",
    "Passenger/crew welfare event",
    "Exercise",
    "Training session"
  ],
  channels: [
    "Phone",
    "Email",
    "WhatsApp",
    "SMS",
    "Web form",
    "In person",
    "Airport desk",
    "Airline office",
    "Other"
  ],
  enquiryTypes: [
    "Information request",
    "Welfare concern",
    "Missing contact",
    "Travel support",
    "Media/legal redirect",
    "Other"
  ],
  enquiryUrgencies: ["Normal", "High", "Urgent welfare"],
  enquiryStatuses: [
    "New",
    "In progress",
    "Sent to family assistance",
    "Duplicate suspected",
    "Urgent welfare",
    "Closed"
  ],
  verificationStatuses: ["Unverified", "Review required", "Verified", "Rejected"],
  personTypes: ["Passenger", "Crew", "Child", "Infant", "Other"],
  genders: ["Female", "Male", "Non-binary", "Unknown", "Other"],
  nationalities: [
    "Polish",
    "British",
    "German",
    "French",
    "Spanish",
    "Italian",
    "Dutch",
    "Czech",
    "Slovak",
    "Hungarian",
    "Lithuanian",
    "Latvian",
    "Estonian",
    "Ukrainian",
    "Romanian",
    "Bulgarian",
    "Turkish",
    "American",
    "Canadian",
    "Israeli",
    "Unknown",
    "Other"
  ],
  relationships: [
    "Spouse / partner",
    "Parent",
    "Child",
    "Sibling",
    "Grandparent",
    "Other relative",
    "Friend",
    "Colleague",
    "Travel companion",
    "Legal representative",
    "Unknown",
    "Other"
  ],
  passengerSources: ["Manifest", "SRC", "Airport", "Station", "Medical", "Manual", "Other"],
  conditionStatuses: ["Unknown", "Uninjured", "Injured", "Hospital", "Released", "Deceased", "Missing"],
  holdTypes: [
    "No hold",
    "Medical hold",
    "Police hold",
    "Security hold",
    "Legal hold",
    "CMT hold",
    "Data quality hold",
    "Identity verification hold",
    "Other"
  ],
  matchingStatuses: [
    "Suggested",
    "Potential match",
    "Verified match",
    "Requires review",
    "Hold / escalate",
    "Rejected",
    "Reunited",
    "Released",
    "Closed / transferred"
  ],
  releaseDestinations: [
    "Family Assistance Centre",
    "Hotel",
    "Home",
    "Hospital",
    "Airport authority",
    "Police",
    "Other"
  ],
  transportModes: ["Walking escorted", "Taxi", "Shuttle", "Ambulance", "Police transfer", "Other"],
  requestCategories: [
    "Transport",
    "Accommodation",
    "Interpreter",
    "Medical",
    "Psychological First Aid",
    "Accessibility",
    "Food / water",
    "Documents",
    "Communication",
    "Other"
  ],
  requestPriorities: ["Low", "Normal", "High", "Urgent"],
  approvalStatuses: ["Not required", "Waiting approval", "Approved", "Rejected"],
  requestStatuses: ["Open", "Assigned", "In progress", "Waiting", "Done", "Closed", "Cancelled"],
  assignmentStatuses: ["Open", "In Progress", "Escalated", "Completed", "Cancelled"],
  assignmentPriorities: ["Normal", "Urgent", "Critical"],
  assignmentFunctions: [
    "Family Assistance",
    "Welfare Support",
    "Telephone Enquiry Center",
    "Passenger / SRC",
    "Matching",
    "Release Control",
    "Rostering",
    "Documentation",
    "Training"
  ],
  exerciseInjectStatuses: ["Planned", "Released", "Completed", "Cancelled"],
  observationAreas: [
    "Intake",
    "Family Assistance",
    "Passenger/SRC",
    "Matching",
    "Requests",
    "Coordination",
    "Other"
  ],
  observationSeverities: ["Low", "Medium", "High"],
  communicationLanguages: ["Polish", "English", "German", "French", "Spanish", "Ukrainian", "Other"]
} as const;

export const sensitiveFields = {
  personalContact: ["phone", "email", "callerPhone", "callerEmail", "ticketNumber", "pnr"],
  decision: ["conditionStatus", "decisionNotes", "verificationNotes", "notes", "matchBasis"],
  medical: ["conditionStatus", "immediateNeeds"]
} as const;

export const auditActions = [
  "login",
  "create_session",
  "update_session",
  "close_session",
  "create_enquiry",
  "send_enquiry_to_family_assistance",
  "mark_urgent",
  "create_family_record",
  "verify_family_record",
  "create_passenger_record",
  "mark_src_confirmed",
  "create_potential_match",
  "verify_match",
  "reject_match",
  "hold_escalate",
  "clear_hold",
  "reunite",
  "release",
  "create_request",
  "assign_request",
  "close_request",
  "create_assignment",
  "update_assignment",
  "assign_assignment",
  "update_assignment_status",
  "create_training_course",
  "update_training_course",
  "deactivate_training_course",
  "reactivate_training_course",
  "create_training_requirement",
  "update_training_requirement",
  "end_training_requirement",
  "assign_training",
  "update_training_record",
  "start_training",
  "complete_training",
  "verify_training",
  "waive_training",
  "cancel_training",
  "create_document",
  "update_document",
  "archive_document",
  "create_document_version",
  "update_document_version",
  "publish_document_version",
  "withdraw_document_version",
  "create_document_requirement",
  "update_document_requirement",
  "end_document_requirement",
  "acknowledge_document",
  "import",
  "export",
  "user_created",
  "user_metadata_changed",
  "user_activated",
  "user_suspended",
  "user_restored",
  "user_archived",
  "member_profile_linked",
  "member_profile_link_changed",
  "member_profile_unlinked",
  "role_assigned",
  "scoped_role_assigned",
  "role_assignment_revoked",
  "role_scope_changed",
  "update_user_roles",
  "custom_role_created",
  "custom_role_changed",
  "custom_role_archived",
  "role_capability_added",
  "role_capability_removed",
  "user_grant_created",
  "user_deny_created",
  "capability_override_revoked",
  "authentication_policy_changed",
  "identity_linked",
  "identity_disabled",
  "identity_unlinked",
  "invitation_prepared",
  "invitation_sent",
  "invitation_resent",
  "invitation_revoked",
  "invitation_accepted",
  "invitation_expired",
  "email_delivery_failed",
  "account_sessions_revoked",
  "organization_change",
  "role_change",
  "dictionary_change"
] as const;

export const workflowStates = {
  completedMatchStatuses: ["Verified match", "Reunited", "Released"],
  pendingMatchStatuses: ["Suggested", "Potential match", "Requires review"],
  terminalRequestStatuses: ["Done", "Closed", "Cancelled", "Completed", "Released", "Reunited", "RESOLVED", "CANCELLED"],
  terminalAssignmentStatuses: ["Completed", "Cancelled"],
  terminalReleaseStatuses: ["Cancelled", "Completed", "Released", "Reunited", "CANCELLED", "COMPLETED"]
} as const;

export type DictionaryKey = keyof typeof dictionaries;
